name: coloring_app
description: Professional coloring app with advanced tools
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  domain:
    path: ./domain
  navigation:
    path: ./navigation

  flutter_native_splash: ^2.4.0

  flutter_bloc: any
dependency_overrides:
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  domain:
    path: ./domain
  data:
    path: ./data
  navigation:
    path: ./navigation
  splash:
    path: ./features/splash
  gallery:
    path: ./features/gallery
  canvas:
    path: ./features/canvas
  settings:
    path: ./features/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "core_ui/resources/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FBFBF9"
  adaptive_icon_foreground: "core_ui/resources/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod

flutter_native_splash:
  color: "#F9F8F6"
  image: core_ui/resources/images/splash_logo.png
  android_12:
    color: "#F9F8F6"
    image: core_ui/resources/images/splash_logo.png
  fullscreen: true
