name: coloring_app
description: Professional coloring app with advanced tools
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core

  flutter_native_splash: ^2.4.0

dependency_overrides:
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  domain:
    path: ./domain
  data:
    path: ./data
  navigation:
    path: ./navigation
  splash:
    path: ./features/splash
  gallery:
    path: ./features/gallery
  canvas:
    path: ./features/canvas
  settings:
    path: ./features/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
