name: feedback
description: Feedback feature for reporting bugs and suggesting ideas
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  image_picker: ^1.2.3
