name: core_ui
description: UI components module
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - resources/fonts/
    - resources/icons/
    - resources/images/