name: core_ui
description: UI components module
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  equatable: ^2.0.5
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - resources/fonts/
    - resources/icons/
    - resources/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: resources/fonts/Montserrat-VariableFont_wght.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: resources/fonts/PlayfairDisplay-VariableFont_wght.ttf